#language: cpp
#
#env:
#  global:
#   - LINUX_DIST=xenial
#
#addons:
# apt:
#  packages:
#   - gcc
#   - cmake
#   - cmake-data
#   - clang
#   - libboost-all-dev
#
#matrix:
#  include:
#    - os: linux
#      dist: xenial
#      sudo: true
#      compiler: clang
#      script:
#       - mkdir -p build
#       - cd build
#       - cmake ..
#       - make
#       - cd ../bin
#       - ./test_runner  --log_level=all --color=true
#
#    - os: linux
#      dist: xenial
#      sudo: true
#      compiler: gcc
#      script:
#       - mkdir -p build
#       - cd build
#       - cmake ..
#       - make
#       - cd ../bin
#       - ./test_runner  --log_level=all --color=true

#install:
#    sudo apt-get install -yf libboost-all-dev clang

# - export CXX=/usr/bin/clang++
# - export CC=/usr/bin/clang


# Use new trusty images, should yield newer compilers and packages
sudo: required
dist: precise
language: cpp

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
      env: COMPILER=g++-4.9
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env: COMPILER=g++-5
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.6
          packages:
            - clang-3.6
      env: COMPILER=clang++-3.6
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.7
          packages:
            - clang-3.7
      env: COMPILER=clang++-3.7

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libboost-all-dev
script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_CXX_COMPILER=$COMPILER .. && make


