sudo: required
language: cpp

matrix:
  include:
    - os: linux
      dist: xenial
      before_install:
        - CXX=/usr/bin/g++
        - CC=/usr/bin/gcc
        - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
        - sudo apt-get update -qq
        - sudo apt-get install -y libboost-all-dev cmake gcc-8 g++-8
        - ls /usr/bin -la

    - os: linux
      dist: xenial
      before_install:
        - CXX=/usr/bin/clang++
        - CC=/usr/bin/clang
        - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
        - sudo apt-get update -qq
        - sudo apt-get install -y libboost-all-dev cmake clang clang-5.0
        - ls /usr/bin -la



#    - compiler: clang
#      addons:
#        apt:
#          sources:
#            - ubuntu-toolchain-r-test
#          packages:
#            - clang
#          env:
#            CXX=/usr/bin/clang++
#            CC=/usr/bin/clang

script:
  - mkdir build
  - cd build
  - cmake ..
  - make
  - cd ../bin
  - ./test_runner --log_level=all --color=true


