sudo: required
os: linux
dist: xenial
language: cpp

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++
          env:
            CXX=/usr/bin/g++
            CC=/usr/bin/gcc
      before_install:
        - sudo apt-get update -qq
        - sudo apt-get install -y libboost-all-dev

    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - clang
          env:
            CXX=/usr/bin/clang++
            CC=/usr/bin/clang

script:
  - mkdir build
  - cd build
  - cmake ..
  - make
  - cd ../bin
  - ./test_runner --log_level=all --color=true


