sudo: required
language: cpp

matrix:
  include:
    - os: linux
      dist: xenial
      env:
        - CXX=/usr/bin/g++
        - CC=/usr/bin/gcc
      before_install:
        - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
        - sudo apt-get update -qq
        - sudo apt-get install -y libboost-all-dev gcc g++ cmake

    - os: linux
      dist: xenial
      env:
        - CXX=/usr/bin/clang++
        - CC=/usr/bin/clang
      before_install:
        - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
        - sudo apt-get update -qq
        - sudo apt-get install -y libboost-all-dev clang-5.0 cmake



#    - compiler: clang
#      addons:
#        apt:
#          sources:
#            - ubuntu-toolchain-r-test
#          packages:
#            - clang
#          env:
#            CXX=/usr/bin/clang++
#            CC=/usr/bin/clang

script:
  - mkdir build
  - cd build
  - cmake ..
  - make
  - cd ../bin
  - ./test_runner --log_level=all --color=true


