sudo: required
language: cpp

matrix:
  include:
    - os: linux
      dist: xenial
      before_install:
        - CC=/usr/bin/gcc-8
        - CXX=/usr/bin/g++-8
        - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
        - sudo apt-get update -qq
        - sudo apt-get install -y libboost-all-dev cmake gcc-8 g++-8

    - os: linux
      dist: xenial
      before_install:
        - CC=/usr/bin/clang-5.0
        - CXX=/usr/bin/clang++-5.0
        - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
        - sudo apt-get update -qq
        - sudo apt-get install -y libboost-all-dev cmake clang clang-5.0

script:
  - mkdir build
  - cd build
  - cmake ..
  - make
  - cd ../bin
  - ./test_runner --log_level=all --color=true
