language: cpp

env:
  global:
   - LINUX_DIST=xenial

addons:
 apt:
  packages:
   - gcc
   - cmake
   - cmake-data
   - clang
   - libboost-all-dev

matrix:
  include:
    - os: linux
      dist: xenial
      sudo: true
      compiler: clang
      script:
       - mkdir -p build
       - cd build
       - cmake ..
       - make
       - cd ../bin
       - ./test_runner  --log_level=all --color=true

    - os: linux
      dist: xenial
      sudo: true
      compiler: gcc
      script:
       - mkdir -p build
       - cd build
       - cmake ..
       - make
       - cd ../bin
       - ./test_runner  --log_level=all --color=true

#install:
#    sudo apt-get install -yf libboost-all-dev clang

# - export CXX=/usr/bin/clang++
# - export CC=/usr/bin/clang


